### ISSUE TITLE
弱弱的说下，我不会用。。。

### ISSUE THREAD

**Issue by WXpiero** [RFG1024/GlossaryGenerator#2]
没有了解过jupyter notebook，所以不知道如何执行，查了jupyter网站，看明白jupyter怎么安装，但是还是不知道怎么使用您这个项目，烦请文档中多写几句，谢谢了

**Comment by RFG1024** [comment]
不属于软件issue范畴。
需要学会基础Python和基础Jupyter Notebook使用方法。
